from fraction import Fraction

f1 = Fraction(num=0, den=-6)
print(f1)
f2 = Fraction(num=2, den=1)
print(f1 + f2)
print(f1 - f2)
print(f1 * f2)
print(f1 / f2)
print(f1 ** f2)
print(f1 == f2)
print(f1.__float__())
print(f1.is_zero())
print(f1.is_integer())
print(f1.is_proper())
print(f1.is_unit())
print(f1.is_adjacent_to(f2))
print(f1.as_mixed_number())
